name: Generate 3D Contributions

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Anbu-Malligarjun-Sri

          SETTING_JSON: |

            {
              "type":"svg",

              "backgroundColor":"#ffffff",

              "colorMap":

              {
                "NONE":"#f5f5f5",
                "FIRST_QUARTILE":"#d1fae5",
                "SECOND_QUARTILE":"#86efac",
                "THIRD_QUARTILE":"#22c55e",
                "FOURTH_QUARTILE":"#15803d"
              }
            }

      - name: Commit Files

        run: |

          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add .

          git commit -m "update graph" || exit 0

          git push
